//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamarinEnterpriseApp.Xamarin.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamarinEnterpriseApp.Xamarin.Core.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Images.
        /// </summary>
        internal static string AddImages {
            get {
                return ResourceManager.GetString("AddImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XamarinEnterprise App.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        internal static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At the level of.
        /// </summary>
        internal static string AtTheHeightOf {
            get {
                return ResourceManager.GetString("AtTheHeightOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to previous screen.
        /// </summary>
        internal static string BackToPreviousScreen {
            get {
                return ResourceManager.GetString("BackToPreviousScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application error occurred..
        /// </summary>
        internal static string BadResponseError {
            get {
                return ResourceManager.GetString("BadResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin.
        /// </summary>
        internal static string Begin {
            get {
                return ResourceManager.GetString("Begin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        internal static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        internal static string ButtonAcc {
            get {
                return ResourceManager.GetString("ButtonAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera is not supported..
        /// </summary>
        internal static string CameraNotSupported {
            get {
                return ResourceManager.GetString("CameraNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Selection.
        /// </summary>
        internal static string CategorySelection {
            get {
                return ResourceManager.GetString("CategorySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution!.
        /// </summary>
        internal static string Caution {
            get {
                return ResourceManager.GetString("Caution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        internal static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose from photo library.
        /// </summary>
        internal static string ChooseFromPhotos {
            get {
                return ResourceManager.GetString("ChooseFromPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your preferred language..
        /// </summary>
        internal static string ChoosePreferredLanguage {
            get {
                return ResourceManager.GetString("ChoosePreferredLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out?.
        /// </summary>
        internal static string ConfirmLogoutMessage {
            get {
                return ResourceManager.GetString("ConfirmLogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectivity Error.
        /// </summary>
        internal static string ConnectivityError {
            get {
                return ResourceManager.GetString("ConnectivityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the internet. Check your internet connection..
        /// </summary>
        internal static string ConnectivityErrorMsg {
            get {
                return ResourceManager.GetString("ConnectivityErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to could not call.
        /// </summary>
        internal static string CouldntMakePhoneCall {
            get {
                return ResourceManager.GetString("CouldntMakePhoneCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        internal static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing here.....
        /// </summary>
        internal static string EditorTextEntryDescription {
            get {
                return ResourceManager.GetString("EditorTextEntryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter {0} here.
        /// </summary>
        internal static string EnterTextInHere {
            get {
                return ResourceManager.GetString("EnterTextInHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please leave a valid email address..
        /// </summary>
        internal static string EnterValidEmailMessage {
            get {
                return ResourceManager.GetString("EnterValidEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid {0}.
        /// </summary>
        internal static string EnterValidField {
            get {
                return ResourceManager.GetString("EnterValidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter {0}.
        /// </summary>
        internal static string EnterValueFor {
            get {
                return ResourceManager.GetString("EnterValueFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value to continue!.
        /// </summary>
        internal static string EnterValueToContinue {
            get {
                return ResourceManager.GetString("EnterValueToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving the data..
        /// </summary>
        internal static string FetchDataErrorMsg {
            get {
                return ResourceManager.GetString("FetchDataErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the field {0} must be filled in.
        /// </summary>
        internal static string FillThisField {
            get {
                return ResourceManager.GetString("FillThisField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred..
        /// </summary>
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started!.
        /// </summary>
        internal static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ImageAcc {
            get {
                return ResourceManager.GetString("ImageAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install a compatible document viewer to view this document..
        /// </summary>
        internal static string InstallDocViewerMessage {
            get {
                return ResourceManager.GetString("InstallDocViewerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install a compatible email app to compose the email..
        /// </summary>
        internal static string InstallEmailViewerMessage {
            get {
                return ResourceManager.GetString("InstallEmailViewerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while connecting to the server..
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Together we keep the neighbourhood clean and safe!.
        /// </summary>
        internal static string Intro1Desc {
            get {
                return ResourceManager.GetString("Intro1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuitenBeter.
        /// </summary>
        internal static string Intro1Header {
            get {
                return ResourceManager.GetString("Intro1Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image of a megaphone.
        /// </summary>
        internal static string Intro1ImageDesc {
            get {
                return ResourceManager.GetString("Intro1ImageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easily create a report on issues like litter, vermin or other issues in the neighbourhood..
        /// </summary>
        internal static string Intro2Desc {
            get {
                return ResourceManager.GetString("Intro2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spotted something?.
        /// </summary>
        internal static string Intro2Header {
            get {
                return ResourceManager.GetString("Intro2Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image of an eye.
        /// </summary>
        internal static string Intro2ImageDesc {
            get {
                return ResourceManager.GetString("Intro2ImageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow your report and recieve updates when your report has been solved..
        /// </summary>
        internal static string Intro3Desc {
            get {
                return ResourceManager.GetString("Intro3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay informed.
        /// </summary>
        internal static string Intro3Header {
            get {
                return ResourceManager.GetString("Intro3Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image of a send message.
        /// </summary>
        internal static string Intro3ImageDesc {
            get {
                return ResourceManager.GetString("Intro3ImageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To make the best use of BuitenBeter we need access to your location and camera..
        /// </summary>
        internal static string Intro4Desc {
            get {
                return ResourceManager.GetString("Intro4Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Intro4Header {
            get {
                return ResourceManager.GetString("Intro4Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image of a thumbs up.
        /// </summary>
        internal static string Intro4ImageDesc {
            get {
                return ResourceManager.GetString("Intro4ImageDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the intro and go to main screen.
        /// </summary>
        internal static string IntroCloseButtonHelpText {
            get {
                return ResourceManager.GetString("IntroCloseButtonHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to next step by double tapping anywhere on the screen.
        /// </summary>
        internal static string IntroDoubleTapToNextScreen {
            get {
                return ResourceManager.GetString("IntroDoubleTapToNextScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to go to main screen.
        /// </summary>
        internal static string IntroGetStartedButtonAcc {
            get {
                return ResourceManager.GetString("IntroGetStartedButtonAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language selection.
        /// </summary>
        internal static string LanguageSelection {
            get {
                return ResourceManager.GetString("LanguageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        internal static string Later {
            get {
                return ResourceManager.GetString("Later", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Data.
        /// </summary>
        internal static string LocationData {
            get {
                return ResourceManager.GetString("LocationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Permission is required for the app to work correctly!.
        /// </summary>
        internal static string LocationRequiredMsg {
            get {
                return ResourceManager.GetString("LocationRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the logo of the {0}.
        /// </summary>
        internal static string LogoGeementeText {
            get {
                return ResourceManager.GetString("LogoGeementeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error.
        /// </summary>
        internal static string LogoutError {
            get {
                return ResourceManager.GetString("LogoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while logging out. Please contact the administrator..
        /// </summary>
        internal static string LogoutErrorMsg {
            get {
                return ResourceManager.GetString("LogoutErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a photo.
        /// </summary>
        internal static string MakePhoto {
            get {
                return ResourceManager.GetString("MakePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory.
        /// </summary>
        internal static string Mandatory {
            get {
                return ResourceManager.GetString("Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Step.
        /// </summary>
        internal static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display.
        /// </summary>
        internal static string NoDataToShow {
            get {
                return ResourceManager.GetString("NoDataToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No list item to display.
        /// </summary>
        internal static string NoListItemToShow {
            get {
                return ResourceManager.GetString("NoListItemToShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string NormalTextAcc {
            get {
                return ResourceManager.GetString("NormalTextAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.A.
        /// </summary>
        internal static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must match the field {1}...
        /// </summary>
        internal static string NotMatchingFields {
            get {
                return ResourceManager.GetString("NotMatchingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Set.
        /// </summary>
        internal static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} does not contain a valid value.
        /// </summary>
        internal static string NotValidField {
            get {
                return ResourceManager.GetString("NotValidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        internal static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please log in to access the push notification.
        /// </summary>
        internal static string PendingPushNotificationMessage {
            get {
                return ResourceManager.GetString("PendingPushNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to edit -.
        /// </summary>
        internal static string PermissionError {
            get {
                return ResourceManager.GetString("PermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App requests permission.
        /// </summary>
        internal static string PermissionRequired {
            get {
                return ResourceManager.GetString("PermissionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while selecting the photo. Please check your rights..
        /// </summary>
        internal static string PickPhotoError {
            get {
                return ResourceManager.GetString("PickPhotoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choosing a photo is not supported..
        /// </summary>
        internal static string PickPhotoNotSupported {
            get {
                return ResourceManager.GetString("PickPhotoNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        internal static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress indicator.
        /// </summary>
        internal static string ProgressIndicator {
            get {
                return ResourceManager.GetString("ProgressIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recidence.
        /// </summary>
        internal static string Recidence {
            get {
                return ResourceManager.GetString("Recidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Credentials.
        /// </summary>
        internal static string RememberCredentials {
            get {
                return ResourceManager.GetString("RememberCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote resource not found..
        /// </summary>
        internal static string RemoteResourceNotFoundError {
            get {
                return ResourceManager.GetString("RemoteResourceNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in at least one field..
        /// </summary>
        internal static string RequiredFieldAnyMissingErrorMessage {
            get {
                return ResourceManager.GetString("RequiredFieldAnyMissingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is a required field..
        /// </summary>
        internal static string RequiredfieldMissingErrorMessage {
            get {
                return ResourceManager.GetString("RequiredfieldMissingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search...
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Category....
        /// </summary>
        internal static string SearchCategory {
            get {
                return ResourceManager.GetString("SearchCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select {0} to continue.
        /// </summary>
        internal static string SelectField {
            get {
                return ResourceManager.GetString("SelectField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select item.
        /// </summary>
        internal static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item to continue.
        /// </summary>
        internal static string SelectItemToContinue {
            get {
                return ResourceManager.GetString("SelectItemToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a language to continue..
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a location.
        /// </summary>
        internal static string SelectLocation {
            get {
                return ResourceManager.GetString("SelectLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select location.
        /// </summary>
        internal static string SelectPlace {
            get {
                return ResourceManager.GetString("SelectPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A verification error has occurred..
        /// </summary>
        internal static string ServerAuthenticationFailedError {
            get {
                return ResourceManager.GetString("ServerAuthenticationFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session has expired. You must log in again..
        /// </summary>
        internal static string SessionExpiredErrorMessage {
            get {
                return ResourceManager.GetString("SessionExpiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Situation.
        /// </summary>
        internal static string Situation {
            get {
                return ResourceManager.GetString("Situation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Introduction.
        /// </summary>
        internal static string SkipIntro {
            get {
                return ResourceManager.GetString("SkipIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By .
        /// </summary>
        internal static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Type.
        /// </summary>
        internal static string SortType {
            get {
                return ResourceManager.GetString("SortType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task cancelled..
        /// </summary>
        internal static string TaskCanceledError {
            get {
                return ResourceManager.GetString("TaskCanceledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number.
        /// </summary>
        internal static string TelephoneNumber {
            get {
                return ResourceManager.GetString("TelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} selected.
        /// </summary>
        internal static string ThisSelected {
            get {
                return ResourceManager.GetString("ThisSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string TitleAcc {
            get {
                return ResourceManager.GetString("TitleAcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app does not have permission to use your camera. You can change this by:
        ///1. Navigate to settings
        ///2. Locate the  app in the list of apps
        ///3. Give the app permission to use your camera..
        /// </summary>
        internal static string TurnOnPermissionInSettings {
            get {
                return ResourceManager.GetString("TurnOnPermissionInSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app does not have permission to use your camera. You can change this by:
        ///1. Navigate to settings
        ///2. Go to apps
        ///3. Look for the  app in the list of apps
        ///4. Go to the permissions of the app
        ///5. Give the app permission to use your camera and/or permission to your storage with photos.
        /// </summary>
        internal static string TurnOnPermissionInSettingsDroid {
            get {
                return ResourceManager.GetString("TurnOnPermissionInSettingsDroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un Checked.
        /// </summary>
        internal static string UnChecked {
            get {
                return ResourceManager.GetString("UnChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this location.
        /// </summary>
        internal static string UseThisLocation {
            get {
                return ResourceManager.GetString("UseThisLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this object.
        /// </summary>
        internal static string UseThisObject {
            get {
                return ResourceManager.GetString("UseThisObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2022 – COMPANY NAME..
        /// </summary>
        internal static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string WaitMsg {
            get {
                return ResourceManager.GetString("WaitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
